# Generated by Django 2.2.28 on 2024-03-20 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=128)),
                ('surname', models.CharField(blank=True, max_length=128)),
                ('country', models.CharField(max_length=128)),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('total_races', models.IntegerField(default=0)),
                ('average_speed', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(max_length=18)),
                ('races_played', models.IntegerField(default=0)),
                ('highscore', models.IntegerField(default=0)),
                ('leaderboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='typerush.Leaderboard')),
            ],
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='players',
            field=models.ManyToManyField(to='typerush.Player'),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='typerush.Mode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='typerush.Player')),
            ],
        ),
    ]
