# Generated by Django 2.2.17 on 2024-02-29 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('typerush', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='firstname',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='player',
            name='surname',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='game',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='typerush.Player'),
        ),
    ]
