# Generated by Django 2.2.28 on 2024-03-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typerush', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='easy_hs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='hard_hs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='medium_hs',
            field=models.IntegerField(default=0),
        ),
    ]
