# Generated by Django 4.2.9 on 2024-03-07 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('typerush', '0002_auto_20240229_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='userID',
            new_name='user',
        ),
    ]
