# Generated by Django 2.2.17 on 2024-03-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typerush', '0003_rename_userid_game_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_images/'),
        ),
    ]
