# Generated by Django 2.2.28 on 2024-03-20 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('typerush', '0004_auto_20240320_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='easy_hs',
        ),
        migrations.RemoveField(
            model_name='player',
            name='hard_hs',
        ),
        migrations.RemoveField(
            model_name='player',
            name='medium_hs',
        ),
    ]
