# Generated by Django 2.2.17 on 2024-03-11 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('typerush', '0006_player_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='slug',
        ),
    ]
