# Generated by Django 2.2.28 on 2024-03-20 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('typerush', '0012_gameresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameResult',
        ),
    ]
